// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Permit_to_work.Data;

#nullable disable

namespace Permit_to_work.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130071616_CreateElectricalIsolationPermit")]
    partial class CreateElectricalIsolationPermit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Permit_to_work.Models.ColdWorkPermitVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractorTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Equipment")
                        .HasColumnType("bit");

                    b.Property<bool>("Falling")
                        .HasColumnType("bit");

                    b.Property<bool>("Faulty")
                        .HasColumnType("bit");

                    b.Property<bool>("Heat")
                        .HasColumnType("bit");

                    b.Property<bool>("Illumination")
                        .HasColumnType("bit");

                    b.Property<bool>("InsuranceAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfWorkmen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Noise")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<bool>("Protruding")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskFallHeight")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlying")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWeather")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tripping")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vibration")
                        .HasColumnType("bit");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColdWorkPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.ElectricalIsolationPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<bool>("ConfinedSpaceRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeEnergizedEquipment")
                        .HasColumnType("bit");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnergizedEquipment")
                        .HasColumnType("bit");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutTagout")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfLocks")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWorkmen")
                        .HasColumnType("int");

                    b.Property<bool>("PPEArcFlash")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEDustMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEEarPlug")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEElectricalGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEFaceShield")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHalfMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<bool>("PowerIsolatedLOTO")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskArcFlash")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectricBurn")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectricShock")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectrocution")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallingObjects")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFire")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlyingParticles")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskManualHandling")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNearOverheadLines")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNoise")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskProtrudingParts")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<bool>("SafeDistanceMaintained")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SwitchOut")
                        .HasColumnType("bit");

                    b.Property<bool>("TestedDeEnergized")
                        .HasColumnType("bit");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voltage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("ElectricalIsolationPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.HotWorkPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FireBlanket")
                        .HasColumnType("bit");

                    b.Property<bool>("FireExtinguisher")
                        .HasColumnType("bit");

                    b.Property<bool>("InsuranceAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<bool>("PPEFaceShield")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPESafetyShoes")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEWeldingGloves")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskArcFlash")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectricShock")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectrocution")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskExplosion")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFireSpark")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlyingParticles")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskManualHandling")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNoise")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<bool>("SafetyBarriers")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WarningSigns")
                        .HasColumnType("bit");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("HotWorkPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.LiftingOperationPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<string>("CapacitySWL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimensionMax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HydraCrane")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<bool>("OverheadCrane")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEDustMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEEarPlug")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEReflectiveVest")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiggerLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskCollapse")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskCrushing")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallingObjects")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskHighWind")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskMovingVehicle")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNearOverheadLines")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNoise")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskOverLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskSuspendedLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskToppling")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTraffic")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TowerCrane")
                        .HasColumnType("bit");

                    b.Property<bool>("TruckMounted")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightApprox")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("LiftingOperationPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.WorkAtHeightPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<bool>("AerialLift")
                        .HasColumnType("bit");

                    b.Property<string>("ContractorTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FallProtection")
                        .HasColumnType("bit");

                    b.Property<bool>("GuardRail")
                        .HasColumnType("bit");

                    b.Property<bool>("HarnessDoubleHook")
                        .HasColumnType("bit");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ladder")
                        .HasColumnType("bit");

                    b.Property<bool>("LifeLine")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<string>("OtherWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PPEDustMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEEarPlug")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmetChinStrap")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEReflectiveVest")
                        .HasColumnType("bit");

                    b.Property<bool>("PPESafetyClothes")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RetractableHarness")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallHeight")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallingObjects")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFaultyEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlyingParticles")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFragileSurface")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskMovingVehicle")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNearOverheadLines")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNonEnergizedEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskProtrudingParts")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWeather")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWorkingBelow")
                        .HasColumnType("bit");

                    b.Property<bool>("RoofWork")
                        .HasColumnType("bit");

                    b.Property<bool>("SafetyNet")
                        .HasColumnType("bit");

                    b.Property<bool>("Scaffolding")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToeBoard")
                        .HasColumnType("bit");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("WorkAtHeightPermits");
                });
#pragma warning restore 612, 618
        }
    }
}
