// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Permit_to_work.Data;

#nullable disable

namespace Permit_to_work.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Permit_to_work.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Permit_to_work.Models.ApprovalStructure", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<string>("ContractorTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("IssuerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<bool>("PPEGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskFallHeight")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlying")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWeather")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("ToolsEquipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApprovalId");

                    b.ToTable("ApprovalStructures");
                });

            modelBuilder.Entity("Permit_to_work.Models.ApproverMaster", b =>
                {
                    b.Property<int>("ApproverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApproverId"));

                    b.Property<string>("ApproverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("LevelIIApprover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelIIIApprover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ApproverId");

                    b.ToTable("ApproverMasters");
                });

            modelBuilder.Entity("Permit_to_work.Models.ColdWorkPermitVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractorTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DocJSA")
                        .HasColumnType("bit");

                    b.Property<string>("DocOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DocRiskAssessment")
                        .HasColumnType("bit");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HazardChemical")
                        .HasColumnType("bit");

                    b.Property<bool>("HazardDust")
                        .HasColumnType("bit");

                    b.Property<bool>("HazardElectrical")
                        .HasColumnType("bit");

                    b.Property<bool>("HazardHotSurface")
                        .HasColumnType("bit");

                    b.Property<bool>("HazardLifting")
                        .HasColumnType("bit");

                    b.Property<string>("HazardNA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HazardScaffolding")
                        .HasColumnType("bit");

                    b.Property<bool>("HazardToolEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("HazardWorkAtHeight")
                        .HasColumnType("bit");

                    b.Property<bool>("InspectAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("InspectDangerSign")
                        .HasColumnType("bit");

                    b.Property<bool>("InspectHandTools")
                        .HasColumnType("bit");

                    b.Property<bool>("InspectLighting")
                        .HasColumnType("bit");

                    b.Property<string>("InspectOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InspectSafetyBarriers")
                        .HasColumnType("bit");

                    b.Property<string>("InspectedNA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IssuerDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfWorkmen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PPEDustMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEEarPlugs")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEGoggles")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHarness")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<string>("PPENA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPEOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PPEReflectiveVest")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<string>("PermitAssociated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermitConfinedSpace")
                        .HasColumnType("bit");

                    b.Property<bool>("PermitElectrical")
                        .HasColumnType("bit");

                    b.Property<bool>("PermitExcavation")
                        .HasColumnType("bit");

                    b.Property<bool>("PermitHotWork")
                        .HasColumnType("bit");

                    b.Property<string>("PermitOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermitWorkAtHeight")
                        .HasColumnType("bit");

                    b.Property<string>("Precaution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallHeight")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFalling")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFaulty")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlying")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskHeat")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskIllumination")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNoise")
                        .HasColumnType("bit");

                    b.Property<string>("RiskOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RiskProtruding")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskVibration")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWeather")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SuspensionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsTested")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WC")
                        .HasColumnType("bit");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColdWorkPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.DepartmentMaster", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("DepartmentMasters");
                });

            modelBuilder.Entity("Permit_to_work.Models.ElectricalIsolationPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<bool>("AccessRoute")
                        .HasColumnType("bit");

                    b.Property<string>("ConfinedSpace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangerSign")
                        .HasColumnType("bit");

                    b.Property<bool>("DeEnergizedEquipment")
                        .HasColumnType("bit");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<string>("ElectricalIsolation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnergizedEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("FireExtinguisher")
                        .HasColumnType("bit");

                    b.Property<string>("FireExtinguisherQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FireExtinguisherSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FireExtinguisherType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuerSignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("JSA")
                        .HasColumnType("bit");

                    b.Property<bool>("Lighting")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutTagout")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfLocks")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWorkmen")
                        .HasColumnType("int");

                    b.Property<string>("OtherDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInsurance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherLOTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherPPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRisk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PPEArcFlash")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEDustMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEEarPlug")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEElectricalGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEFaceShield")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHalfMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEReflectiveVest")
                        .HasColumnType("bit");

                    b.Property<bool>("PPESafetyEar")
                        .HasColumnType("bit");

                    b.Property<bool>("PPESafetyGoggles")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PermitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Precaution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceiverSignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RiskArcFlash")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskAssessment")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectricBurn")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectricShock")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskElectrocution")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallingObjects")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFire")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlyingParticles")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskManualHandling")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNoise")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskOverheadLines")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskProtrudingParts")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<string>("SafeDistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SafetyBarriers")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SuspensionSignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SwitchOut")
                        .HasColumnType("bit");

                    b.Property<bool>("TestConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToolsTested")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voltage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WC")
                        .HasColumnType("bit");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("ElectricalIsolationPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.HotWorkPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<bool>("Apron")
                        .HasColumnType("bit");

                    b.Property<bool>("AttachJSA")
                        .HasColumnType("bit");

                    b.Property<string>("AttachOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AttachRiskAssessment")
                        .HasColumnType("bit");

                    b.Property<bool>("ChippingCuttingGrinding")
                        .HasColumnType("bit");

                    b.Property<string>("CombustibleRemoved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CylindersProvided")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<string>("ESIFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EarPlugs")
                        .HasColumnType("bit");

                    b.Property<string>("EmergencyContact1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyTeamAvailable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FaceShield")
                        .HasColumnType("bit");

                    b.Property<bool>("FireBlanketChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("FireExtinguisherChecked")
                        .HasColumnType("bit");

                    b.Property<string>("FireExtinguisherDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashbackArrestors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GasMask")
                        .HasColumnType("bit");

                    b.Property<bool>("Helmet")
                        .HasColumnType("bit");

                    b.Property<bool>("HosesCutCrack")
                        .HasColumnType("bit");

                    b.Property<bool>("HosesFreeGrease")
                        .HasColumnType("bit");

                    b.Property<string>("HosesNA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HosesSpecialClips")
                        .HasColumnType("bit");

                    b.Property<string>("IsWelderCertified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LightingChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<string>("OtherPPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precaution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regulator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegulatorNA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SafetyBarriersChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("SafetyShoes")
                        .HasColumnType("bit");

                    b.Property<bool>("SandBucketChecked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionSignatureDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsTested")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WC")
                        .HasColumnType("bit");

                    b.Property<string>("WCFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WarningSignChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("Welding")
                        .HasColumnType("bit");

                    b.Property<bool>("WeldingClothes")
                        .HasColumnType("bit");

                    b.Property<bool>("WeldingGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("WeldingGoggles")
                        .HasColumnType("bit");

                    b.Property<bool>("WeldingShield")
                        .HasColumnType("bit");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("HotWorkPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.LiftingOperationPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<bool>("AdverseWeather")
                        .HasColumnType("bit");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedCompletionTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FallingObjects")
                        .HasColumnType("bit");

                    b.Property<bool>("Helmet")
                        .HasColumnType("bit");

                    b.Property<bool>("HydraCrane")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadDimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadWeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<string>("OtherRisk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OverheadCrane")
                        .HasColumnType("bit");

                    b.Property<bool>("Overload")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceiverDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReflectiveVest")
                        .HasColumnType("bit");

                    b.Property<bool>("SafetyShoes")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionSignatureDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Toppling")
                        .HasColumnType("bit");

                    b.Property<bool>("TruckMounted")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WC")
                        .HasColumnType("bit");

                    b.HasKey("PermitId");

                    b.ToTable("LiftingOperationPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.Login", b =>
                {
                    b.Property<int>("loginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loginId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("loginId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Permit_to_work.Models.PermitMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("PermitMasters");
                });

            modelBuilder.Entity("Permit_to_work.Models.PermitTypeMaster", b =>
                {
                    b.Property<int>("PermitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitTypeId"));

                    b.Property<string>("PermitTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("PermitTypeId");

                    b.ToTable("PermitTypeMasters");
                });

            modelBuilder.Entity("Permit_to_work.Models.UnitMaster", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("UnitId");

                    b.ToTable("UnitMasters");
                });

            modelBuilder.Entity("Permit_to_work.Models.WorkAtHeightPermit", b =>
                {
                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermitId"));

                    b.Property<bool>("AccessProvided")
                        .HasColumnType("bit");

                    b.Property<bool>("AerialLift")
                        .HasColumnType("bit");

                    b.Property<bool>("BuddySystem")
                        .HasColumnType("bit");

                    b.Property<string>("ContractorTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangerWarningSign")
                        .HasColumnType("bit");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FallProtection")
                        .HasColumnType("bit");

                    b.Property<bool>("FloorOpeningsCovered")
                        .HasColumnType("bit");

                    b.Property<bool>("GuardRail")
                        .HasColumnType("bit");

                    b.Property<bool>("GuardRailsSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("HarnessDoubleHook")
                        .HasColumnType("bit");

                    b.Property<bool>("HarnessShockAbsorber")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ladder")
                        .HasColumnType("bit");

                    b.Property<bool>("LifeLine")
                        .HasColumnType("bit");

                    b.Property<bool>("Lighting")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaterialBasket")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfWorkmen")
                        .HasColumnType("int");

                    b.Property<string>("OtherInspection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRiskControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PPEDustMask")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEEarPlug")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEHelmetChinStrap")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEReflectiveVest")
                        .HasColumnType("bit");

                    b.Property<bool>("PPESafetyClothes")
                        .HasColumnType("bit");

                    b.Property<bool>("PPEShoes")
                        .HasColumnType("bit");

                    b.Property<string>("Precaution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceiverDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rescue")
                        .HasColumnType("bit");

                    b.Property<bool>("RetractableHarness")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskControlImplemented")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallHeight")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFallingObjects")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFaultyEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFlyingParticles")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskFragileSurface")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskMovingVehicle")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNearOverheadLines")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskNonEnergizedEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskProtrudingParts")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskTripping")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWeather")
                        .HasColumnType("bit");

                    b.Property<bool>("RiskWorkingBelow")
                        .HasColumnType("bit");

                    b.Property<string>("Riskcontrol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RoofWork")
                        .HasColumnType("bit");

                    b.Property<bool>("SafetyBarriers")
                        .HasColumnType("bit");

                    b.Property<bool>("SafetyNet")
                        .HasColumnType("bit");

                    b.Property<bool>("ScaffoldCertified")
                        .HasColumnType("bit");

                    b.Property<bool>("ScaffoldTagSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("Scaffolding")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionSignatureDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToeBoard")
                        .HasColumnType("bit");

                    b.Property<string>("ToolsEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WC")
                        .HasColumnType("bit");

                    b.Property<bool>("WindGreater32")
                        .HasColumnType("bit");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermitId");

                    b.ToTable("WorkAtHeightPermits");
                });

            modelBuilder.Entity("Permit_to_work.Models.PermitMaster", b =>
                {
                    b.HasOne("Permit_to_work.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
